# Generated by Django 5.2.11 on 2026-02-26 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('event_type', models.CharField(blank=True, choices=[('boda', 'Boda'), ('cumpleanos', 'Cumpleaños infantil'), ('comunion', 'Comunión'), ('corporativo', 'Evento corporativo'), ('festival', 'Festival / Fiesta'), ('sesion', 'Sesión de fotos'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de evento')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Fecha del evento')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Recibido')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número = aparece primero.', verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(help_text='Describe la imagen para SEO y accesibilidad.', max_length=200, verbose_name='Texto alternativo')),
                ('category', models.CharField(choices=[('facepainting', 'Facepainting'), ('halloween', 'Halloween'), ('bodypaint', 'Body Paint'), ('bellypaint', 'Belly Paint'), ('glitterbar', 'Glitter Bar')], max_length=20, verbose_name='Categoría')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Pie de foto')),
                ('order', models.PositiveIntegerField(default=0, help_text='Menor número = aparece primero.', verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(help_text='Nombre interno (home, nosotros, galeria, etc.). No cambiar.', max_length=50, unique=True, verbose_name='Identificador de página')),
                ('title', models.CharField(help_text='Aparece en la pestaña del navegador y en Google. Máximo ~60 caracteres.', max_length=70, verbose_name='Title (SEO)')),
                ('meta_description', models.CharField(help_text='Resumen que aparece en Google bajo el título. Máximo ~155 caracteres.', max_length=160, verbose_name='Meta description')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=200, verbose_name='OG Description')),
            ],
            options={
                'verbose_name': 'SEO de página',
                'verbose_name_plural': 'SEO de páginas',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identificador URL (ej: facepainting, bodypaint). No cambiar.', unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('tagline', models.CharField(help_text='Frase corta que aparece bajo el título en la home.', max_length=200, verbose_name='Eslogan')),
                ('description', models.TextField(help_text='Texto largo para la página individual del servicio.', verbose_name='Descripción')),
                ('card_image', models.ImageField(blank=True, help_text='Imagen que aparece en la tarjeta de servicios de la home.', upload_to='services/', verbose_name='Imagen de tarjeta')),
                ('hero_image', models.ImageField(blank=True, help_text='Imagen grande de la cabecera de la página del servicio.', upload_to='services/', verbose_name='Imagen hero')),
                ('is_external', models.BooleanField(default=False, help_text='Si es externo (Tatuajes, Belly), se enlaza a otra web.', verbose_name='Servicio externo')),
                ('external_url', models.URLField(blank=True, help_text='Solo si es servicio externo.', verbose_name='URL externa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['order'],
            },
        ),
    ]
